import { Injectable } from '@angular/core';
import { Usuario } from '../clases/usuario';
import { Chofer } from '../clases/chofer';

@Injectable({
  providedIn: 'root'
})
export class UsersService {

  private master = {"Usuario" : "Admin", "Contrasenia" : "Ifts.ds24?"};
  private usuarios : Usuario[] = [];

  public getMasterUser(){
    return this.master.Usuario;
  }

  public getMasterContra(){
    return this.master.Contrasenia;
  }

  public getUsuarios(){
    return this.usuarios;
  }

  public getUsuarioIndex(i : number){
    return this.usuarios[i];
  }

  public modificarChofer(c: Chofer){
    for(let i = 0; i < this.usuarios.length; i++){
      if(this.usuarios[i].chofer?.legajo == c.legajo){
        this.usuarios[i].chofer = c;
      }
    }
  }

  public agregarUsuario(u : Usuario){
    this.usuarios.push(u);
  }

  public borrarUsuario(legajo : number | undefined){
    for(let i = 0; i < this.usuarios.length; i++){
      if(this.usuarios[i].chofer?.legajo == legajo){
        this.usuarios.splice(i,1);
      }
    }
  }

  constructor() { }

  public inicioChoferes(){
    let choferes : Chofer[] = [{
      "dni": 1,
      "legajo": 46537,
      "nombre": "Starlene",
      "apellido": "Denisovo",
      "fechaNac": "2/22/1995"
    }, {
      "dni": 2,
      "legajo": 3984,
      "nombre": "Naomi",
      "apellido": "Gable",
      "fechaNac": "6/4/1999"
    }, {
      "dni": 3,
      "legajo": 0,
      "nombre": "Arney",
      "apellido": "Quesne",
      "fechaNac": "9/16/1988"
    }, {
      "dni": 4,
      "legajo": 505,
      "nombre": "Tessa",
      "apellido": "Gallagher",
      "fechaNac": "11/5/1989"
    }, {
      "dni": 5,
      "legajo": 929,
      "nombre": "Edgar",
      "apellido": "Descroix",
      "fechaNac": "11/15/1982"
    }, {
      "dni": 6,
      "legajo": 132,
      "nombre": "Deanne",
      "apellido": "Trustrie",
      "fechaNac": "8/26/1985"
    }, {
      "dni": 7,
      "legajo": 45110,
      "nombre": "Felice",
      "apellido": "MacCauley",
      "fechaNac": "9/23/1982"
    }, {
      "dni": 8,
      "legajo": 4517,
      "nombre": "Pen",
      "apellido": "Schubbert",
      "fechaNac": "7/3/1987"
    }, {
      "dni": 9,
      "legajo": 2459,
      "nombre": "Lotty",
      "apellido": "Hillburn",
      "fechaNac": "4/4/1999"
    }, {
      "dni": 10,
      "legajo": 29625,
      "nombre": "Waneta",
      "apellido": "Paulson",
      "fechaNac": "11/12/1991"
    }, {
      "dni": 11,
      "legajo": 10081,
      "nombre": "Kacey",
      "apellido": "Hullock",
      "fechaNac": "2/2/1983"
    }, {
      "dni": 12,
      "legajo": 605,
      "nombre": "Lelah",
      "apellido": "Cubitt",
      "fechaNac": "7/26/1995"
    }, {
      "dni": 13,
      "legajo": 441,
      "nombre": "Myron",
      "apellido": "Spiers",
      "fechaNac": "11/5/1980"
    }, {
      "dni": 14,
      "legajo": 73,
      "nombre": "Karil",
      "apellido": "Bletcher",
      "fechaNac": "1/5/1994"
    }, {
      "dni": 15,
      "legajo": 680,
      "nombre": "Rosalia",
      "apellido": "Ditch",
      "fechaNac": "1/13/1984"
    }, {
      "dni": 16,
      "legajo": 33,
      "nombre": "Parry",
      "apellido": "Dinesen",
      "fechaNac": "9/4/1995"
    }, {
      "dni": 17,
      "legajo": 9,
      "nombre": "Berry",
      "apellido": "Ruit",
      "fechaNac": "11/6/1991"
    }, {
      "dni": 18,
      "legajo": 727,
      "nombre": "Devlin",
      "apellido": "Allwell",
      "fechaNac": "12/2/1985"
    }, {
      "dni": 19,
      "legajo": 152,
      "nombre": "Dane",
      "apellido": "Turnpenny",
      "fechaNac": "10/22/1992"
    }, {
      "dni": 20,
      "legajo": 6,
      "nombre": "Lisbeth",
      "apellido": "Bohlsen",
      "fechaNac": "11/23/1980"
    }, {
      "dni": 21,
      "legajo": 38660,
      "nombre": "Annecorinne",
      "apellido": "Cadogan",
      "fechaNac": "7/6/1993"
    }, {
      "dni": 22,
      "legajo": 7816,
      "nombre": "Felicio",
      "apellido": "Nickoll",
      "fechaNac": "9/3/1988"
    }, {
      "dni": 23,
      "legajo": 29126,
      "nombre": "Clyde",
      "apellido": "Robichon",
      "fechaNac": "3/27/1988"
    }, {
      "dni": 24,
      "legajo": 48,
      "nombre": "Elizabet",
      "apellido": "Style",
      "fechaNac": "2/28/1982"
    }, {
      "dni": 25,
      "legajo": 5,
      "nombre": "Fredek",
      "apellido": "Brazer",
      "fechaNac": "8/20/1982"
    }, {
      "dni": 26,
      "legajo": 8276,
      "nombre": "Kerrin",
      "apellido": "Kenright",
      "fechaNac": "2/3/1999"
    }, {
      "dni": 27,
      "legajo": 220,
      "nombre": "Ruprecht",
      "apellido": "Extill",
      "fechaNac": "3/21/1990"
    }, {
      "dni": 28,
      "legajo": 92394,
      "nombre": "Liuka",
      "apellido": "Whithorn",
      "fechaNac": "8/23/1988"
    }, {
      "dni": 29,
      "legajo": 85026,
      "nombre": "Terrel",
      "apellido": "Bailey",
      "fechaNac": "5/10/1991"
    }, {
      "dni": 30,
      "legajo": 731,
      "nombre": "Vyky",
      "apellido": "O'Hannigan",
      "fechaNac": "5/16/1987"
    }, {
      "dni": 31,
      "legajo": 874,
      "nombre": "Millie",
      "apellido": "Hebbard",
      "fechaNac": "5/15/1984"
    }, {
      "dni": 32,
      "legajo": 89,
      "nombre": "Keane",
      "apellido": "Townshend",
      "fechaNac": "12/23/1988"
    }, {
      "dni": 33,
      "legajo": 6,
      "nombre": "Ashil",
      "apellido": "Blyde",
      "fechaNac": "5/28/1996"
    }, {
      "dni": 34,
      "legajo": 17,
      "nombre": "Ricky",
      "apellido": "Aishford",
      "fechaNac": "9/6/1997"
    }, {
      "dni": 35,
      "legajo": 6,
      "nombre": "Tadd",
      "apellido": "Screech",
      "fechaNac": "3/22/1984"
    }, {
      "dni": 36,
      "legajo": 8705,
      "nombre": "Harriett",
      "apellido": "Marusyak",
      "fechaNac": "12/27/1992"
    }, {
      "dni": 37,
      "legajo": 48,
      "nombre": "Trish",
      "apellido": "Glynne",
      "fechaNac": "8/3/1990"
    }, {
      "dni": 38,
      "legajo": 76,
      "nombre": "Jeanie",
      "apellido": "Mustin",
      "fechaNac": "10/27/1981"
    }, {
      "dni": 39,
      "legajo": 675,
      "nombre": "Kile",
      "apellido": "Pech",
      "fechaNac": "1/31/1992"
    }, {
      "dni": 40,
      "legajo": 3650,
      "nombre": "Sylvia",
      "apellido": "Ortsmann",
      "fechaNac": "8/14/1994"
    }, {
      "dni": 41,
      "legajo": 0,
      "nombre": "Tonia",
      "apellido": "Spawforth",
      "fechaNac": "12/25/1988"
    }, {
      "dni": 42,
      "legajo": 1115,
      "nombre": "Kacey",
      "apellido": "Buglar",
      "fechaNac": "12/2/1999"
    }, {
      "dni": 43,
      "legajo": 82543,
      "nombre": "Kendre",
      "apellido": "Reddings",
      "fechaNac": "9/27/1997"
    }, {
      "dni": 44,
      "legajo": 7,
      "nombre": "Marybelle",
      "apellido": "Gouny",
      "fechaNac": "2/29/1996"
    }, {
      "dni": 45,
      "legajo": 6,
      "nombre": "Lynnelle",
      "apellido": "Threadgill",
      "fechaNac": "12/22/1994"
    }, {
      "dni": 46,
      "legajo": 562,
      "nombre": "Torrin",
      "apellido": "Annakin",
      "fechaNac": "12/27/1990"
    }, {
      "dni": 47,
      "legajo": 6,
      "nombre": "Welch",
      "apellido": "Scrace",
      "fechaNac": "10/25/1998"
    }, {
      "dni": 48,
      "legajo": 8,
      "nombre": "Felicia",
      "apellido": "McClaren",
      "fechaNac": "9/17/1981"
    }, {
      "dni": 49,
      "legajo": 7452,
      "nombre": "Cindy",
      "apellido": "Wrigglesworth",
      "fechaNac": "2/7/1987"
    }, {
      "dni": 50,
      "legajo": 1247,
      "nombre": "Yolande",
      "apellido": "Mignot",
      "fechaNac": "4/3/1981"
    }];
  
    let usrs : Usuario[] = [{
      "usuario": "gdillimore0",
      "mail": "achampness0@tumblr.com",
      "contrasenia": "XD5K4UP",
      "chofer": choferes[0],
    }, {
      "usuario": "mkingwell1",
      "mail": "igrady1@biglobe.ne.jp",
      "contrasenia": "6NjaCGkJq",
      "chofer": choferes[1]
    },{
      "usuario": "jebbutt1d",
      "mail": "slardner1d@about.com",
      "contrasenia": "zk2Rqg",
      "chofer": choferes[2]
    }, {
      "usuario": "bjedrzejewski2",
      "mail": "cjumel2@thetimes.co.uk",
      "contrasenia": "bgwEr8",
      "chofer": choferes[3]
    }, {
      "usuario": "lturton3",
      "mail": "mkettle3@so-net.ne.jp",
      "contrasenia": "KSdZGh4Rw",
      "chofer": choferes[4]
    }, {
      "usuario": "cgalpin4",
      "mail": "pigonet4@shop-pro.jp",
      "contrasenia": "rIYDABfYb",
      "chofer": choferes[5]
    }, {
      "usuario": "vtitta5",
      "mail": "rdeeming5@so-net.ne.jp",
      "contrasenia": "0ksgDkKARXG5",
      "chofer": choferes[6]
    }, {
      "usuario": "ewank6",
      "mail": "nower6@twitpic.com",
      "contrasenia": "hEA1WjnQrE",
      "chofer": choferes[7]
    }, {
      "usuario": "rdowda7",
      "mail": "skiessel7@e-recht24.de",
      "contrasenia": "lcLJngn",
      "chofer": choferes[8]
    }, {
      "usuario": "rpickavance8",
      "mail": "lambroziak8@weebly.com",
      "contrasenia": "xtku6VA",
      "chofer": choferes[9]
    }, {
      "usuario": "lpahler9",
      "mail": "nausiello9@simplemachines.org",
      "contrasenia": "OU3Aa8Xrbz",
      "chofer": choferes[10]
    }, {
      "usuario": "crowlstonea",
      "mail": "malgiea@1688.com",
      "contrasenia": "EFkFMGMQyEg",
      "chofer": choferes[11]
    }, {
      "usuario": "oprobetb",
      "mail": "ebabbeb@facebook.com",
      "contrasenia": "Cf02q1",
      "chofer": choferes[12]
    }, {
      "usuario": "lskrzynskic",
      "mail": "ccrichtenc@chicagotribune.com",
      "contrasenia": "DMMQsx",
      "chofer": choferes[13]
    }, {
      "usuario": "gballanced",
      "mail": "jprestond@gmpg.org",
      "contrasenia": "2TpFdxTbpJ",
      "chofer": choferes[14]
    }, {
      "usuario": "fmaccoveneye",
      "mail": "qbloye@cargocollective.com",
      "contrasenia": "lUgo4oOx",
      "chofer": choferes[15]
    }, {
      "usuario": "scaldecotf",
      "mail": "bhillyattf@twitpic.com",
      "contrasenia": "VjFFofPcgM",
      "chofer": choferes[16]
    }, {
      "usuario": "wkinnearg",
      "mail": "pdivisg@youku.com",
      "contrasenia": "8ik5HyBp",
      "chofer": choferes[17]
    }, {
      "usuario": "pclearsh",
      "mail": "jfulbrookh@twitter.com",
      "contrasenia": "j2slCpyn8",
      "chofer": choferes[18]
    }, {
      "usuario": "bohallagani",
      "mail": "kmcgrirli@patch.com",
      "contrasenia": "CFQDDQ3MfoE",
      "chofer": choferes[19]
    }, {
      "usuario": "xmckinleyj",
      "mail": "emariaudj@bbc.co.uk",
      "contrasenia": "cn7AKrNcK",
      "chofer": choferes[20]
    }, {
      "usuario": "imccuisk",
      "mail": "bviank@wordpress.org",
      "contrasenia": "6kl98aiqAVNz",
      "chofer": choferes[21]
    }, {
      "usuario": "rcoulesl",
      "mail": "rciscol@engadget.com",
      "contrasenia": "yGDRULKTIKJ",
      "chofer": choferes[22]
    }, {
      "usuario": "aburbridgem",
      "mail": "zhurichem@reddit.com",
      "contrasenia": "SsgYfI",
      "chofer": choferes[23]
    }, {
      "usuario": "hcalverdn",
      "mail": "lblackebyn@narod.ru",
      "contrasenia": "kXnm61whfQA",
      "chofer": choferes[24]
    }, {
      "usuario": "obarnsono",
      "mail": "cgoldingayo@umn.edu",
      "contrasenia": "jkAkI4Hi",
      "chofer": choferes[25]
    }, {
      "usuario": "isplavenp",
      "mail": "vjardeinp@posterous.com",
      "contrasenia": "gVe541Ifwgg",
      "chofer": choferes[26]
    }, {
      "usuario": "gpinchbeckq",
      "mail": "nhordellq@linkedin.com",
      "contrasenia": "j85ceZvJo69",
      "chofer": choferes[27]
    }, {
      "usuario": "wtiner",
      "mail": "mmonkleyr@youtube.com",
      "contrasenia": "jyh3fIzHOm",
      "chofer": choferes[28]
    }, {
      "usuario": "dbarwiss",
      "mail": "sjudkinss@tinyurl.com",
      "contrasenia": "dSJEUs",
      "chofer": choferes[29]
    }, {
      "usuario": "ynordasst",
      "mail": "sshoveltont@ted.com",
      "contrasenia": "ujAbwz4dP",
      "chofer": choferes[30]
    }, {
      "usuario": "speddaru",
      "mail": "sabramamovhu@thetimes.co.uk",
      "contrasenia": "8F2HpIi18Y",
      "chofer": choferes[31]
    }, {
      "usuario": "bsolomonv",
      "mail": "dcaineyv@upenn.edu",
      "contrasenia": "GhunKz",
      "chofer": choferes[32]
    }, {
      "usuario": "gectorw",
      "mail": "solwenw@google.cn",
      "contrasenia": "QUBCMcV2",
      "chofer": choferes[33]
    }, {
      "usuario": "kraperx",
      "mail": "ldoberx@biglobe.ne.jp",
      "contrasenia": "Sl5fnp",
      "chofer": choferes[34]
    }, {
      "usuario": "mfawloey",
      "mail": "mbrazery@exblog.jp",
      "contrasenia": "Cy1FqeBAeBzu",
      "chofer": choferes[35]
    }, {
      "usuario": "dissacovz",
      "mail": "whurstz@baidu.com",
      "contrasenia": "DptisR6nAd6F",
      "chofer": choferes[36]
    }, {
      "usuario": "bgristwood10",
      "mail": "cwalklot10@photobucket.com",
      "contrasenia": "OMZ08JW6",
      "chofer": choferes[37]
    }, {
      "usuario": "vjeacock11",
      "mail": "neard11@cbsnews.com",
      "contrasenia": "TIcmc2RXp",
      "chofer": choferes[38]
    }, {
      "usuario": "tshergill12",
      "mail": "ldelabarre12@alexa.com",
      "contrasenia": "NLtWQYJYBsX",
      "chofer": choferes[39]
    }, {
      "usuario": "abrocks13",
      "mail": "gfallow13@marketwatch.com",
      "contrasenia": "jjzVrxyTAQi",
      "chofer": choferes[40]
    }, {
      "usuario": "dwarrender14",
      "mail": "bbyas14@mozilla.com",
      "contrasenia": "sLKhUu6",
      "chofer": choferes[41]
    }, {
      "usuario": "iduchasteau15",
      "mail": "hescritt15@businesswire.com",
      "contrasenia": "tGGRG8",
      "chofer": choferes[42]
    }, {
      "usuario": "epainter16",
      "mail": "acrown16@sogou.com",
      "contrasenia": "8SiCU8qhWiqP",
      "chofer": choferes[43]
    }, {
      "usuario": "fwesthoff17",
      "mail": "ylemmer17@toplist.cz",
      "contrasenia": "f0UCPqaLSRt",
      "chofer": choferes[44]
    }, {
      "usuario": "tspondley18",
      "mail": "hmcillrick18@cnet.com",
      "contrasenia": "Sgm0fb",
      "chofer": choferes[45]
    }, {
      "usuario": "itowler19",
      "mail": "eaddey19@uol.com.br",
      "contrasenia": "WDIQA4ZNvwJ",
      "chofer": choferes[46]
    }, {
      "usuario": "schaloner1a",
      "mail": "kdarington1a@arstechnica.com",
      "contrasenia": "cBR4vNs",
      "chofer": choferes[47]
    }, {
      "usuario": "rgregolin1b",
      "mail": "pinchley1b@archive.org",
      "contrasenia": "MjQXb5TWvji",
      "chofer": choferes[48]
    }, {
      "usuario": "fdanbye1c",
      "mail": "gpimblotte1c@github.io",
      "contrasenia": "OSC66z",
      "chofer": choferes[49]
    }];
  
    for(let i = 0; i < usrs.length; i++){
      this.usuarios.push(usrs[i]);
    }
  }

}
